### ISSUE TITLE
i2c.SetSpeed doesn't really check for error

### ISSUE THREAD

**Issue by tenox7** [rafalop/sevensegment#6]
https://github.com/rafalop/sevensegment/blob/49807d1bd894ab5f68d28e8ae157da31d6787a76/sevensegment.go#L25

the way the statement is written `err` is not assigned from `b.SetSpeed()` and therefore `err != nil` doesn't reference err from `SetSpeed()`:

```
		if b.SetSpeed(100 * physic.KiloHertz); err != nil {
```

To work correctly it should be:

```
		if err = b.SetSpeed(100 * physic.KiloHertz); err != nil {
```

However this always returns an error. The library currently works because it silently fails to set speed. I'm no expert but I think this could just be safely removed? I can send a CL but I'm not sure of the speed needs to be changed to 100 kHz?

**Comment by rafalop** [comment]
Yeah i'm not sure to be honest, it's been a long time since i wrote it and i can't remember what i was trying to achieve by setting the bus speed. so you played with setting the speed and it always returns a non nil error? it might depend on the platform. maybe some raspberry pi models don't support changing bus speed.

in any case i think you're right, it looks like err is always nil when it reaches there and i don't remember a good reason for setting the speed, so perhaps we can just remove it.

**Comment by tenox7** [comment]
Okay I changed it to just a warning:

```
		if err = b.SetSpeed(100 * physic.KiloHertz); err != nil {
			log.Print(err)
		}
```

Tested on:

- Zero W
- 3B+
- 4B

In all cases it prints our the error and works fine without setting the speed.

The error is:

```
2022/04/29 20:11:07 bcm283x: to change the I²C bus speed, please refer to https://periph.io/platform/raspberrypi/#i²c
```

According to the link https://periph.io/platform/raspberrypi/#i%C2%B2c seems that changing the speed is not even required? I think maybe there is a performance penalty but in case of this display this shouldn't be a problem. 

I'm going to send a PR to remove this 🤷
